name: Test and Commit Coverage Badge

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-and-commit-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests with coverage
        run: yarn test:coverage

      - name: Generate coverage badge JSON
        run: |
          mkdir -p .coverage
          LINES=$(jq '.total.lines.pct' coverage/coverage-summary.json)
          FUNCTIONS=$(jq '.total.functions.pct' coverage/coverage-summary.json)
          STATEMENTS=$(jq '.total.statements.pct' coverage/coverage-summary.json)
          BRANCHES=$(jq '.total.branches.pct' coverage/coverage-summary.json)
          echo "{
            \"schemaVersion\": 1,
            \"label\": \"coverage\",
            \"color\": \"brightgreen\",
            \"total\": {
              \"lines\": { \"pct\": $LINES },
              \"functions\": { \"pct\": $FUNCTIONS },
              \"statements\": { \"pct\": $STATEMENTS },
              \"branches\": { \"pct\": $BRANCHES }
            }
          }" > .coverage/coverage-badge.json

      - name: Commit and push coverage badge
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .coverage/coverage-badge.json
          git commit -m "chore: update coverage badge [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
